//AddSong("Artist Name","Song Name","Genre Name","File lovation in terms of songs/","Image location","Album Name")
//    "Album Name" should be the same file in img/albums/ to display the image

AddSong("Aero Chord","4U","Moombahton","AeroChord_4U.mp3","img/artists/aerochord.png","4usingle")
AddSong("Aero Chord","Boundless","Trap","AeroChord_Boundless.mp3","img/artists/aerochord.png","boundlesssingle")
AddSong("Aero Chord","Surface","Trap","AeroChord_Surface.mp3","img/artists/aerochord.png","surfacesingle")
AddSong("Aero Chord","The 90S","Future Bass","AeroChord_The90S.mp3","img/artists/aerochord.png","loveandhateep")
AddSong("Aero Chord &<br>Razihel","Titans","Trap","AeroChordAndRazihel_Titans.mp3","img/artists/aerochord.png","titanssingle")
AddSong("Aero Chord","Wanchu Back","Trap","AeroChord_WanchuBack.mp3","img/artists/aerochord.png","loveandhateep")

AddSong("Au5","Crossroad<br>(feat. Danyka Nadeau)","Trance","Au5_Crossroad.mp3","img/artists/au5.png","crossroadsingle")
AddSong("Au5","Snowblind<br>(feat. Tasha Baxter)","Dubstep","Au5_Snowblind.mp3","img/artists/au5.png","snowblindsingle")

AddSong("Astronaut","Apollo<br>(Radio Edit)","Electro","Astronaut_ApolloRadioEdit.mp3","img/artists/astronaut.png","apolloep")
AddSong("Astronaut","Champions<br>(feat. Harry Brooks Jnr)","House","Astronaut_Champions.mp3","img/artists/astronaut.png","championssingle")
AddSong("Astronaut","Feronia<br>(feat. Danyka Nadeau)","Electro","Astronaut_Feronia.mp3","img/artists/astronaut.png","feroniasingle")
AddSong("Astronaut","Quantum","Electro","Astronaut_Quantum.mp3","img/artists/astronaut.png","quantumep")
AddSong("Astronaut","Quantum<br>(Hellberg Remix)","Progressive House","Astronaut_QuantumHellbergRemix.mp3","img/artists/astronaut.png","destinationquantum")
AddSong("Astronaut","Quantum<br>(Virtual Riot Remix)","Dubstep","Astronaut_QuantumVirtualRiotRemix.mp3","img/artists/astronaut.png","destinationquantum")
AddSong("Astronaut","Rain<br>(MitiS Remix)","Drumstep","Astronaut_RainMitiSRemix.mp3","img/artists/astronaut.png","destinationrain")
AddSong("Astronaut","Rain<br>(Stephen Walking Remix)","Glitch Hop or 110 BPM","Astronaut_RainStephenWalkingRemix.mp3","img/artists/astronaut.png","destinationrain")
AddSong("Astronaut & Far Too Loud","War<br>(F.O.O.L & Didrick Remix)","Electro","AstronautAndFarTooLoud_WarFOOLAndDidrickRemix.mp3","img/artists/astronaut.png","destinationwar")

AddSong("Botnek &<br>I See MONSTAS","Deeper Love","Drum & Bass","BotnekAndISeeMONSTAS_DeeperLove.mp3","img/artists/botnek.png","deeperlovesingle")

AddSong("Case & Point","Fugitive","Electro","CaseAndPoint_Fugitive.mp3","img/artists/caseandpoint.png","fugitivesingle")
AddSong("Case & Point","Upgrade","Electro","CaseAndPoint_Upgrade.mp3","img/artists/caseandpoint.png","upgradeep")

AddSong("DotEXE","Inside Out","Trap","DotEXE_InsideOut.mp3","img/artists/dotexe.png","insideoutsingle")

AddSong("Draper","Pressure<br>(feat. Laura Brehm)","EDM","Draper_Pressure.mp3","img/artists/draper.png","pressuresingle")
AddSong("Draper","Ready For Us<br>(feat. Sykes) ","Indie Dance","Draper_ReadyForUs.mp3","img/artists/draper.png","readyforussingle")

AddSong("Droptek &<br>Tut Tut Child","Drop That Child","Dubstep","DroptekAndTutTutChild_DropThatChild.mp3","img/artists/tuttutchild.png","dropthatchildsingle")

AddSong("Ephixa & Stephen Walking","Matches<br>(feat. Aaron Richards)","Indie Dance","EphixaAndStephenWalking_Matches.mp3","img/artists/ephixa.png","monstercat5yearanniversary")

AddSong("F.O.O.L","Fairytaler","Dubstep","FOOL_Fairytaler.mp3","img/artists/fool.png","knightep")
AddSong("F.O.O.L","Feelings<br>(Lets Be Friends Remix)","Electro","FOOL_FeelingsLetsBeFriendsRemix.mp3","img/artists/fool.png","feelingsep")
AddSong("F.O.O.L","Get Down","Electro","FOOL_GetDown.mp3","img/artists/fool.png","feelingsep")
AddSong("F.O.O.L","Keep On Rocking","Electro","FOOL_KeepOnRocking.mp3","img/artists/fool.png","keeponrockingsingle")
AddSong("F.O.O.L","Need You","Electro","FOOL_NeedYou.mp3","img/artists/fool.png","needyousingle")
AddSong("F.O.O.L","Showdown","Electro","FOOL_Showdown.mp3","img/artists/fool.png","showdownsingle")
AddSong("F.O.O.L","Throne","Electro","FOOL_Throne.mp3","img/artists/fool.png","thronesingle")

AddSong("Grabbitz","Better With Time","EDM","Grabbitz_BetterWithTime.mp3","img/artists/grabbitz.png","betterwithtimeep")
AddSong("Grabbitz","Float Away","Indie Dance","Grabbitz_FloatAway.mp3","img/artists/grabbitz.png","betterwithtimeep")
AddSong("Grabbitz","Friends<br>(feat. Faustix)","Trap","Grabbitz_Friends.mp3","img/artists/grabbitz.png","friendsep")
AddSong("Grabbitz","Here With You Now","Dubstep","Grabbitz_HereWithYouNow.mp3","img/artists/grabbitz.png","friendsep")
AddSong("Grabbitz","Turn Around","Dubstep","Grabbitz_TurnAround.mp3","img/artists/grabbitz.png","friendsep")

AddSong("Grant Bowtie","Reach","Future Bass","GrantBowtie_Reach.mp3","img/artists/grantbowtie.png","reachsingle")

AddSong("Hellberg, Teqq &<br> Taylr Renne","Air<br>(Hellberg's Back To Summer Mix)","Progressive House","HellbergTeqqAndTaylrRenee_AirHellbergsBackToSummerMix.mp3","img/artists/hellberg.png","airhellbergsbacktosummermixsingle")
AddSong("Hellberg & Rich Edwards","Ashes (Burn Your Love)<br>(feat. Danyka Nadeau)","Progressive House","HellbergAndRichEdwards_AshesBurnYourLove.mp3","img/artists/hellberg.png","ashessingle")
AddSong("Hellberg","Follow My Heart","Progressive House","Hellberg_FollowMyHeart.mp3","img/artists/hellberg.png","monstercat011revolution")
AddSong("Hellberg","Get Up","Progressive House","Hellberg_GetUp.mp3","img/artists/hellberg.png","monstercat012aftermath")
AddSong("Hellberg &<br>Rich Edwards","Hands Of Time","Progressive House","HellbergAndRichEdwards_HandsOfTime.mp3","img/artists/hellberg.png","handsoftimesingle")
AddSong("Hellberg","I'm Not Over<br>(feat. Tash)","Progressive House","Hellberg_ImNotOver.mp3","img/artists/hellberg.png","imnotoversingle")
AddSong("Hellberg","Saviors","Progressive House","Hellberg_Saviors.mp3","img/artists/hellberg.png","saviorssingle")
AddSong("Hellberg","The Girl<br>(feat. Cozi Zeuhlsdoff)","Progressive House","Hellberg_TheGirl.mp3","img/artists/hellberg.png","thisismeep")
AddSong("Hellberg","The Girl (feat. Cozi Zeuhlsdoff)<br>(Color Source Remix)","Future Bass","Hellberg_TheGirlColorSourceRemix.mp3","img/artists/hellberg.png","thegirltheremixes")

AddSong("Hot Date! & Insan3Lik3","Clocks<br>(feat. Chrisson)","Electro","HotDateAndInsan3Lik3_Clocks.mp3","img/artists/hotdate.png","monstercat008anniversary")
AddSong("Hot Date! & Chrisson","Overcome<br>(This Time)","Drum & Bass","HotDateAndChrisson_OvercomeThisTime.mp3","img/artists/hotdate.png","monstercat006embrace")
AddSong("Hot Date! & Chrisson","To The Sun<br>(feat. Roufaida)","Drum & Bass","HotDateAndChrisson_ToTheSun.mp3","img/artists/hotdate.png","monstercat011revolution")

AddSong("Tristam X Karma Fields","Build The Cities (Empire Of Sound)<br>(feat. Kerli)","Electro","TristamXKarmaFields_BuildTheCitiesEmpireOfSound.mp3","img/artists/karmafields.png","buildthecitiesreconstructions")
AddSong("Karma Fields","Build The Cities<br>(feat. Kerli)","Electro","KarmaFields_BuildTheCities.mp3","img/artists/karmafields.png","newagedarkage")
AddSong("Karma Fields","Build The Cities (feat. Kerli)<br>(Project 46 Remix)","Progressive House","KarmaFields_BuildTheCitiesProject46Remix.mp3","img/artists/karmafields.png","buildthecitiesreconstructions")
AddSong("Karma Fields","Build The Cities (feat. Kerli)<br>(Rootkit Remix)","Future House","KarmaFields_BuildTheCitiesRootkitRemix.mp3","img/artists/karmafields.png","buildthecitiesreconstructions")
AddSong("Karma Fields","Edge Of The World","Electro","KarmaFields_EdgeOfTheWorld.mp3","img/artists/karmafields.png","newagedarkage")
AddSong("Karma Fields","For Me","Electro","KarmaFields_ForMe.mp3","img/artists/karmafields.png","newagedarkage")
AddSong("Karma Fields & MORTEN","Stickup (feat. Juliette Lewis)<br>(Modestep Remix)","Drumstep","KarmaFieldsAndMORTEN_StickupModestepRemix.mp3","img/artists/karmafields.png","stickupsingle")

AddSong("Laszlo","A King's Life","Progressive House","Laszlo_AKingsLife.mp3","img/artists/laszlo.png","closerep")
AddSong("Laszlo","Airglow","Future House","Laszlo_Airglow.mp3","img/artists/laszlo.png","airglowsingle")
AddSong("Laszlo","Closer","EDM","Laszlo_Closer.mp3","img/artists/laszlo.png","closerep")
AddSong("Laszlo","Don't Look Down","Drum & Bass","Laszlo_DontLookDown.mp3","img/artists/laszlo.png","dontlookdownsingle")
AddSong("Laszlo","Fall To Light","Progressive House","Laszlo_FallToLight.mp3","img/artists/laszlo.png","falltolightsingle")
AddSong("Laszlo","Here We Are","Drum & Bass","Laszlo_HereWeAre.mp3","img/artists/laszlo.png","herewearesingle")
AddSong("Laszlo","Home<br>(feat. Richard Caddock)","Progressive House","Laszlo_Home.mp3","img/artists/laszlo.png","homesingle")
AddSong("Laszlo","Interstellar","Progressive House","Laszlo_Interstellar.mp3","img/artists/laszlo.png","interstellarsingle")
AddSong("Laszlo","Sphere","Progressive House","Laszlo_Sphere.mp3","img/artists/laszlo.png","spheresingle")
AddSong("Laszlo","Supernova","Electro","Laszlo_Supernova.mp3","img/artists/laszlo.png","supernovasingle")
AddSong("Laszlo","Tribal","House","Laszlo_Tribal.mp3","img/artists/laszlo.png","monstercat5yearanniversary")
AddSong("Laszlo X WRLD","You & Me","Future Bass","LaszloXWRLD_YouAndMe.mp3","img/artists/laszlo.png","youandmesingle")

AddSong("Lets Be Friends","FTW","Electro","LetsBeFriends_FTW.mp3","img/artists/letsbefriends.png","ftwsingle")
AddSong("Lets Be Friends","Manslaughter<br/>(VIP Mix)","Glitch Hop Or 110 BPM","LetsBeFriends_ManslaughterVipMix.mp3","img/artists/letsbefriends.png","monstercat014discovery")

AddSong("Marshmello","Alone","Trap","Marshmello_Alone.mp3","img/artists/marshmello.png","alonesingle")
AddSong("Marshmello","Alone<br>(MRVLZ Remix)","Future Bass","Marshmello_AloneMRVLZRemix.mp3","img/artists/marshmello.png","alonetheremixes")
AddSong("Marshmello","Alone<br>(Streex Remix)","Future Bass","Marshmello_AloneStreexRemix.mp3","img/artists/marshmello.png","alonetheremixes")

AddSong("Mitchell Claxton","Koh Samui","Trance","MitchellClaxton_KohSamui.mp3","img/artists/mitchellclaxton.png","monstercat009reunion")
AddSong("Mitchell Claxton","Wuxia","Trance","MitchellClaxton_Wuxia.mp3","img/artists/mitchellclaxton.png","wuxiasingle")

AddSong("Muzzy & Day One","Black Magic","Drum & Bass","MuzzyAndDayOne_BlackMagic.mp3","img/artists/muzzy.png","monstercat008anniversary")
AddSong("Muzzy","Calling Out<br>(feat. KG & Skyelle)","Drum & Bass","Muzzy_CallingOut.mp3","img/artists/muzzy.png","callingoutsingle")
AddSong("Muzzy","Children Of Hell","Drum & Bass","Muzzy_ChildrenOfHell.mp3","img/artists/muzzy.png","fminorfactoryep")
AddSong("Muzzy","Crescendo<br>(feat. MYLK)","Drum & Bass","Muzzy_Crescendo.mp3","img/artists/muzzy.png","monstercat5yearanniversary")
AddSong("Muzzy","Feeling Stronger (feat. Charlotte Colley)<br>(High Maintenance Remix)","Drum & Bass","Muzzy_FeelingStrongerHighMaintenanceRemix.mp3","img/artists/muzzy.png","getcrazyfeelingstrongertheremixes")
AddSong("Muzzy","Insignia","Trap","Muzzy_Insignia.mp3","img/artists/muzzy.png","insigniasingle")
AddSong("Muzzy","Junction Seven","Drumstep","Muzzy_JunctionSeven.mp3","img/artists/muzzy.png","fminorfactoryep")
AddSong("Muzzy","Letz Rock","Drum & Bass","Muzzy_LetzRock.mp3","img/artists/muzzy.png","letzrockep")
AddSong("Muzzy & Roniit","Pegasus","Drum & Bass","MuzzyAndRoniit_Pegasus.mp3","img/artists/muzzy.png","letzrockep")
AddSong("Muzzy","Play<br>(ft. UK:ID)","Drum & Bass","Muzzy_Play.mp3","img/artists/muzzy.png","fminorfactoryep")
AddSong("Muzzy","The Phantom<br>(feat. High Maintenance)","Drum & Bass","Muzzy_ThePhantom.mp3","img/artists/muzzy.png","thetakeoverep")

AddSong("Nitro Fun","Cheat Codes","Electro","NitroFun_CheatCodes.mp3","img/artists/nitrofun.png","cheatcodessingle")
AddSong("Nitro Fun &<br>Hyper Potions","Checkpoint","Electro","NitroFunAndHyperPotions_Checkpoint.mp3","img/artists/nitrofun.png","checkpointsingle")
AddSong("Nitro Fun","Final Boss","Electro","NitroFun_FinalBoss.mp3","img/artists/nitrofun.png","finalbosssingle")
AddSong("Nitro Fun","New Game","Electro","NitroFun_NewGame.mp3","img/artists/nitrofun.png","newgamesingle")
AddSong("Nitro Fun","Soldiers","House","NitroFun_Soldiers.mp3","img/artists/nitrofun.png","soldierssingle")

AddSong("Noisestorm","Barracuda","Breaks","Noisestorm_Barracuda.mp3","img/artists/noisestorm.png","barracudasingle")
AddSong("Noisestorm","Heist","Trap","Noisestorm_Heist.mp3","img/artists/noisestorm.png","heistsingle")
AddSong("Noisestorm","Leaving Now","Drum & Bass","Noisestorm_LeavingNow.mp3","img/artists/noisestorm.png","leavingnowsingle")
AddSong("Noisestorm","Sentinel","Breaks","Noisestorm_Sentinel.mp3","img/artists/noisestorm.png","sentinelsingle")
AddSong("Noisestorm","Surge","Electro","Noisestorm_Surge.mp3","img/artists/noisestorm.png","surgesingle")
AddSong("Noisestorm","This Feeling","Electro","Noisestorm_ThisFeeling.mp3","img/artists/noisestorm.png","monstercat5yearanniversary")

AddSong("Project 46","No One<br>(feat. Matthew Steeper)","Progressive House","Project46_NoOne.mp3","img/artists/project46.png","monstercat012aftermath")
AddSong("Project 46","Reasons<br>(feat. Andrew Allen)","House","Project46_Reasons.mp3","img/artists/project46.png","reasonssingle")

AddSong("Pegboard Nerds &<br>Grabbitz","All Alone","Drumstep","PegboardNerdsAndGrabbitz_AllAlone.mp3","img/artists/pegboardnerds.png","allalonesingle")
AddSong("Pegboard Nerds","Badboi","Trap","PegboardNerds_Badboi.mp3","img/artists/pegboardnerds.png","badboisingle")
AddSong("Pegboard Nerds","Badboi<br>(Snavs Remix)","Trap","PegboardNerds_BadboiSnavsRemix.mp3","img/artists/pegboardnerds.png","theuncagedremixes")
AddSong("Pegborad Nerds","Bassline Kickin<br>(Astronaut Remix)","Electro","PegboardNerds_BasslineKickinAstronautRemix.mp3","img/artists/pegboardnerds.png","basslinekickintheremixes")
AddSong("Pegborad Nerds","Bassline Kickin","EDM","PegboardNerds_BasslineKickin.mp3","img/artists/pegboardnerds.png","basslinekickinsingle")
AddSong("Pegboard Nerds","Blackout","Electro","PegboardNerds_Blackout.mp3","img/artists/pegboardnerds.png","monstercat5yearanniversary")
AddSong("Pegboard Nerds","Downhearted<br>(feat. Jonny Rose)","Dubstep","PegboardNerds_Downhearted.mp3","img/artists/pegboardnerds.png","pinkcloudep")
AddSong("Pegboard Nerds","Downhearted (feat. Jonny Rose)<br>(MIU Remix)","Dubstep","PegboardNerds_DownheartedMIURemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Downhearted (feat. Jonny Rose)<br>(Morgan Page Remix)","Progressive House","PegboardNerds_DownheartedMorganPageRemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Downhearted (feat. Jonny Rose)<br>(Ryos Remix)","Future Bass","PegboardNerds_DownheartedRyosRemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Emergency","Electro","PegboardNerds_Emergency.mp3","img/artists/pegboardnerds.png","emergencysingle")
AddSong("Pegboard Nerds","Emoji","Future Bass","PegboardNerds_Emoji.mp3","img/artists/pegboardnerds.png","pinkcloudep")
AddSong("Pegboard Nerds","Emoji<br>(Rogue Remix)","Future Bass","PegboardNerds_EmojiRogueRemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Emoji<br>($unday $ervice Remix)","Future Bass","PegboardNerds_EmojiSundayServiceRemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Heartbit<br>(feat. Tia Simone)","Electro","PegboardNerds_Heartbit.mp3","img/artists/pegboardnerds.png","heartbitsingle")
AddSong("Pegboard Nerds","Heartbit (feat. Tia Simone)<br>(MIU Remix)","Dubstep","PegboardNerds_HeartbitMIURemix.mp3","img/artists/pegboardnerds.png","heartbittheremixes")
AddSong("Pegboard Nerds","Here It Comes<br>(Snavs & Toby Green Remix)","Trap","PegboardNerds_HereItComesSnavsAndTobyGreenRemix.mp3","img/artists/pegboardnerds.png","theuncagedremixes")
AddSong("Pegboard Nerds","Just Like That<br>(feat. Johnny Graves)","Future Bass","PegboardNerds_JustLikeThat.mp3","img/artists/pegboardnerds.png","pinkcloudep")
AddSong("Pegboard Nerds","Just Like That (feat. Johnny Graves)<br>(Two Friends Remix)","Progressive House","PegboardNerds_JustLikeThatTwoFriendsRemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds","Luigi's Mansion","Dubstep","PegboardNerds_LuigisMansion.mp3","img/artists/pegboardnerds.png","luigismansionsingle")
AddSong("Pegboard Nerds","New Style","EDM","PegboardNerds_NewStyle.mp3","img/artists/pegboardnerds.png","newstylesingle")
AddSong("Pegboard Nerds","Pink Cloud<br>(feat. Max Collins)","Indie Dance","PegboardNerds_PinkCloud.mp3","img/artists/pegboardnerds.png","pinkcloudep")
AddSong("Pegboard Nerds","Pink Cloud (feat. Max Collins)<br>(FKYA Remix)","EDM","PegboardNerds_PinkCloudFKYARemix.mp3","img/artists/pegboardnerds.png","pinkcloudtheremixes")
AddSong("Pegboard Nerds<br>& Tristam","Razor Sharp","Glitch Hop Or 110 BPM","PegboardNerdsAndTristam_RazorSharp.mp3","img/artists/pegboardnerds.png","razorsharpsingle")
AddSong("Pegboard Nerds & Tristam","Razor Sharp VIP<br>(Vocal Mix)","Glitch Hop Or 110 BPM","PegboardNerdsAndTristam_RazorSharpVIPVocalMix.mp3","img/artists/pegboardnerds.png","razorsharpvocalmixsingle")
AddSong("Pegboard Nerds","Revenge Of The Nerds<br>(VIP Mix)","Dubstep","PegboardNerds_RevengeOfTheNerdsVIPMix.mp3","img/artists/pegboardnerds.png","thelosttracksep")
AddSong("Pegborad Nerds","Self Destruct","Dubstep","PegboardNerds_SelfDestruct.mp3","img/artists/pegboardnerds.png","monstercat010conquest")
AddSong("Pegboard Nerds <br>& NGHTMRE","Superstar","Dubstep","PegboardNerdsAndNGHTMRE_Superstar.mp3","img/artists/pegboardnerds.png","superstarsingle")
AddSong("Pegboard Nerds","Swamp Thing","EDM","PegboardNerds_SwampThing.mp3","img/artists/pegboardnerds.png","swampthingsingle")
AddSong("Pegboard Nerds","Try This","Drumstep","PegboardNerds_TryThis.mp3","img/artists/pegboardnerds.png","trythissingle")
AddSong("Pegboard Nerds","We Are One<br>(Droptek Remix)","Electro","PegboardNerds_WeAreOneDroptekRemix.mp3","img/artists/pegboardnerds.png","monstercat012aftermath")
AddSong("Pegboard Nerds &<br>MIU","Weaponize","Dubstep","PegboardNerdsAndMIU_Weaponize.mp3","img/artists/pegboardnerds.png","weaponizesingle")

AddSong("Puppet & Foria","I'm Here","Indie Dance","PuppetAndForia_ImHere.mp3","img/artists/puppet.png","imheresingle")
AddSong("Puppet &<br>The Eden Project","The Fire","Electro","PuppetAndTheEdenProject_TheFire.mp3","img/artists/puppet.png","thefiresingle")

AddSong("Razihel","Children Of The Night","Bounce","Razihel_ChildrenOfTheNight.mp3","img/artists/razihel.png","childrenofthenightsingle")
AddSong("Razihel","Legends","Trap","Razihel_Legends.mp3","img/artists/razihel.png","legendssingle")
AddSong("Razihel","Legends<br>(Hyper Potions Remix)","Future Bass","Razihel_LegendsHyperPotionsRemix.mp3","img/artists/razihel.png","legendshyperpotionsremixsingle")
AddSong("Razihel","Legends<br>(Zatox Remix)","Hard Dance","Razihel_LegendsZatoxRemix.mp3","img/artists/razihel.png","legendszatoxremixsingle")

AddSong("Richard Caddock, WRLD, Nitro Fun,<br> Slips & Slurs & Subtact","Break The Silence","Future Bass","RichardCaddockWRLDNitroFunSlipsAndSlursSubtact_BreakTheSilence.mp3","img/artists/richardcaddock.png","monstercat5yearanniversary")

AddSong("Rootkit","Against The Sun<br>(feat. Anna Yvette)","Drumstep","Rootkit_AgainstTheSun.mp3","img/artists/rootkit.png","againstthesunsingle")
AddSong("Rootkit","Real Love<br>(feat. Danyka Nadeau)","Future House","Rootkit_RealLove.mp3","img/artists/rootkit.png","reallovesingle")

AddSong("Rogue","Air","Dubstep","Rogue_Air.mp3","img/artists/rogue.png","dreamsep")
AddSong("Rogue","Atlantic","Electro","Rogue_Atlantic.mp3","img/artists/rogue.png","atlanticsingle")
AddSong("Rogue","Dreams<br>(feat. Laura Brehm)","Drumstep","Rogue_Dreams.mp3","img/artists/rogue.png","dreamsep")
AddSong("Rogue","Drive Away","EDM","Rogue_DriveAway.mp3","img/artists/rogue.png","driveawaysingle")
AddSong("Rogue","From The Dust","Drumstep","Rogue_FromTheDust.mp3","img/artists/rogue.png","earthep")
AddSong("Rogue","Imperfect Views","EDM","Rogue_ImperfectViews.mp3","img/artists/rogue.png","monstercat5yearanniversary")
AddSong("Rogue","Moments<br>(feat. Meg Dean)","House","Rogue_Moments.mp3","img/artists/rogue.png","dreamsep")
AddSong("Rogue","Nightfall","Glitch Hop Or 110 BPM","Rogue_Nightfall.mp3","img/artists/rogue.png","monstercat012aftermath")
AddSong("Rogue","Rattlesnake","Trap","Rogue_Rattlesnake.mp3","img/artists/rogue.png","rattlesnakesingle")
AddSong("Rogue","Through The Dark","Electro","Rogue_ThroughTheDark.mp3","img/artists/rogue.png","earthep")

AddSong("SCNDL","The Munsta","Bounce","SCNDL_TheMunsta.mp3","img/artists/scndl.png","themunstasingle")
AddSong("SCNDL","The Munsta<br>(AlphavibeZ Remix)","Hard Dance","SCNDL_TheMunstaAlphavibeZRemix.mp3","img/artists/scndl.png","themunstatheremixesep")

AddSong("Snails <br>& Pegboard Nerds","Deep In The Night","Dubstep","SnailsAndPegboardNerds_DeepInTheNight.mp3","img/artists/snails.png","deepinthenightsingle")

AddSong("SMLE","Halo<br>(feat. Helen Tess)","Future Bass","SMLE_Halo.mp3","img/artists/smle.png","halosingle")

AddSong("Slips & Slurs","Divided","Trap","SlipsAndSlurs_Divided.mp3","img/artists/slipsandslurs.png","dividedsingle")
AddSong("Slips & Slurs","Divided VIP","Trap","SlipsAndSlurs_DividedVIP.mp3","img/artists/slipsandslurs.png","monstercat5yearanniversary")
AddSong("Slips & Slurs","Malicious","EDM","SlipsAndSlurs_Malicious.mp3","img/artists/slipsandslurs.png","malicioussingle")

AddSong("Stephen Walking","Birthday Cake","Electro","StephenWalking_BirthdayCake.mp3","img/artists/stephenwalking.png","monstercat006embrace")
AddSong("Stephen Walking","It Came From Planet Earth","Electro","StephenWalking_ItCameFromPlanetEarth.mp3","img/artists/stephenwalking.png","itcamefromplanetearthsingle")
AddSong("Stephen Walking","Light Pollution","Dubstep","StephenWalking_LightPollution.mp3","img/artists/stephenwalking.png","monstercat002earlystage")
AddSong("Stephen Walking","Metropolis","Dubstep","StephenWalking_Metropolis.mp3","img/artists/stephenwalking.png","monstercat002earlystage")
AddSong("Stephen Walking","One Man Moon Band","EDM","StephenWalking_OneManMoonBand.mp3","img/artists/stephenwalking.png","onemanmoonbandsingle")
AddSong("Stephen Walking","Porkchop Express","EDM","StephenWalking_PorkchopExpress.mp3","img/artists/stephenwalking.png","porkchopexpresssingle")
AddSong("Stephen Walking<br>& Hyper Potions","Saturday Morning Space Ride","Future Bass","StephenWalkingAndHyperPotions_SaturdayMorningSpaceRide.mp3","img/artists/stephenwalking.png","saturdaymorningspaceridesingle")
AddSong("Stephen Walking","The Difference Between Us And The<br>Aliens","EDM","StephenWalking_TheDifferenceBetweenUsAndTheAliens.mp3","img/artists/stephenwalking.png","thedifferencebetweenusandthealienssingle")
AddSong("Stephen Walking","Top Of The World 2","Electro","StephenWalking_TopOfOheWorld2.mp3","img/artists/stephenwalking.png","topoftheworld2single")

AddSong("Stonebank","All Night<br>(feat. EMEL)","Hard Dance","Stonebank_AllNight.mp3","img/artists/stonebank.png","allnightsingle")
AddSong("Stonebank","Be Alright<br>(feat. EMEL)","Hard Dance","Stonebank_BeAlright.mp3","img/artists/stonebank.png","bealrightsingle")
AddSong("Stonebank","Chokehold<br>(feat. Concept)","Glitch Hop Or 110 BPM","Stonebank_Chokehold.mp3","img/artists/stonebank.png","monumentep")
AddSong("Stonebank","Lift You Up<br>(feat. EMEL)","Trance","Stonebank_LiftYouUp.mp3","img/artists/stonebank.png","monstercat5yearanniversary")
AddSong("Stonebank","Stronger<br>(feat. EMEL)","Hardcore","Stonebank_Stronger.mp3","img/artists/stonebank.png","strongersingle")
AddSong("Stonebank","The Only One<br>(feat. Ben Clark)","Hardstyle","Stonebank_TheOnlyOne.mp3","img/artists/stonebank.png","theonlyonesingle")
AddSong("Stonebank","Who's Got Your Love","Happy Hardcore","Stonebank_WhosGotYourLove.mp3","img/artists/stonebank.png","whosgotyourlovesingle")

AddSong("Summer Was Fun","Hold On<br>(feat. Q'aila)","Indie Dance","SummerWasFun_HoldOn.mp3","img/artists/summerwasfun.png","holdonsingle")
AddSong("Summer Was Fun","Pick Up The Phone","Indie Dance","SummerWasFun_PickUpThePhone.mp3","img/artists/summerwasfun.png","pickupthephonesingle")
AddSong("Summer Was Fun","Run To You<br>(feat. Meron Ryan)","House","SummerWasFun_RunToYou.mp3","img/artists/summerwasfun.png","runtoyousingle")
AddSong("Summer Was Fun","Watching<br>(feat. Colordrive)","Indie Dance","SummerWasFun_Watching.mp3","img/artists/summerwasfun.png","watchingsingle")

AddSong("Tristam","Before We Fade","EDM","Tristam_BeforeWeFade.mp3","img/artists/tristam.png","monstercat5yearanniversary")
AddSong("Tristam","Crave","Electro House","Tristam_Crave.mp3","img/artists/tristam.png","cravesingle")
AddSong("Tristam & Braken","Flight","Drumstep","TristamAndBraken_Flight.mp3","img/artists/tristam.png","monstercat012aftermath")
AddSong("Tristam & Braken","Frame Of Mind","Drum & Bass","TristamAndBraken_FrameOfMind.mp3","img/artists/tristam.png","frameofmindsingle")
AddSong("Tristam","The Vine","Drumstep","Tristam_TheVine.mp3","img/artists/tristam.png","thevinesingle")
AddSong("Tristam","Once Again","Glitch Hop Or 110 BPM","Tristam_OnceAgain.mp3","img/artists/tristam.png","monstercat016expedition")
AddSong("Tristam","Till It's Over","Glitch Hop Or 110 BPM","Tristam_TillItsOver.mp3","img/artists/tristam.png","tillitsoversingle")
AddSong("Tristam","Truth","Electro","Tristam_Truth.mp3","img/artists/tristam.png","monstercat010conquest")

AddSong("Tut Tut Child","Dance To It","Glitch Hop Or 110 BPM","TutTutChild_DanceToIt.mp3","img/artists/tuttutchild.png","dancetoitep")
AddSong("Tut Tut Child","Dragon Pirates","Drumstep","TutTutChild_DragonPirates.mp3","img/artists/tuttutchild.png","dancetoitep")
AddSong("Tut Tut Child","Drink Up","Glitch Hop Or 110 BPM","TutTutChild_DrinkUp.mp3","img/artists/tuttutchild.png","drinkupsingle")
AddSong("Tut Tut Child","Hot Pursuit","Electro","TutTutChild_HotPursuit.mp3","img/artists/tuttutchild.png","askyourfriendsfirstep")
AddSong("Tut Tut Child","Maelstrom","Drumstep","TutTutChild_Maelstrom.mp3","img/artists/tuttutchild.png","monstercat007solace")
AddSong("Tut Tut Child","Power Fracture","EDM","TutTutChild_PowerFracture.mp3","img/artists/tuttutchild.png","powerfracturesingle")
AddSong("Tut Tut Child","The Uppity Strut","Glitch Hop Or 110 BPM","TutTutChild_TheUppityStrut.mp3","img/artists/tuttutchild.png","theuppitystrutsingle")

AddSong("Vicetone","Heartbeat<br>(feat. Collin McLoughlin)","Progressive House","Vicetone_Heartbeat.mp3","img/artists/vicetone.png","monstercat012aftermath")
AddSong("Vicetone","Nevada<br>(feat. Cozi Zuehlsdorff)","Progressive House","Vicetone_Nevada.mp3","img/artists/vicetone.png","nevadasingle")

AddSong("Varien &<br>7 Minutes Dead","Mirai Sekai (Continuous Mix)","EDM","VarienAnd7MinutesDead_MiraiSekaiContinuousMix.mp3","img/artists/varien.png","miraisekaiep")
AddSong("Varien","Valkyrie<br>(feat. Laura Brehm)","Drumstep","Varien_Valkyrie.mp3","img/artists/varien.png","valkyriesingle")
